### ISSUE TITLE
How to fix this? 

### ISSUE THREAD

**Issue by 1stdevfriend** [sinscary/Flask-Social-Networking#1]
![screenshot from 2018-04-26 01-08-46](https://user-images.githubusercontent.com/27912312/39268828-976b2930-48ee-11e8-8a4a-2119b8ae9706.png)

**Comment by Mayank2904** [comment]
i am also  facing same issue.

**Comment by sinscary** [comment]
Will try to fix it soon. seems an issue with an update in peewee.
